spring.application.name=nha_grant
spring.datasource.url=jdbc:postgresql://localhost:5432/grant_request?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=Varad@6422

server.servlet.context-path=/api