spring.application.name=nha_grant
server.servlet.context-path=/v1/api

#tcl
#spring.datasource.url=jdbc:postgresql://100.96.57.195:5444/nhagrants?currentSchema=public
#spring.datasource.username=appadmin
#spring.datasource.password=Nhahpr@196

#aws
spring.datasource.url=jdbc:postgresql://abdm-intsbx-aps1-aupsql-common-1.cluster-cb68q6euihs4.ap-south-1.rds.amazonaws.com:5432/nhagrants?currentSchema=public
spring.datasource.username=commonuser
spring.datasource.password=ULRD83SIfsolOlnl

rsa.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsjnG4r8Q8X1/C+wM8vFHiaJpnmt7/nLuAlUhaI9SLAvsCnHehiWV7YamwYFuA/0OoogH56ZBFucSUhfSeexzKEm2LifT+jy7gctFaRz+vxItNi5e8SQZHVBNL+bHDYfyfWUOUCVsQFTPDAh+ui3se3TO8+7cLe7XGoHHI/OuIOb9z5qYpvH4jISXPqd5nw8A9eLcwkLO+MGeyYqOfUbl4lOQ9XbAdP5bSyR/qiDKPL3uXq0ajVZLNnA1mMnZ+cq+TT9jaHi5jnKnnrAfRRt3lwqX2c0AwLfzSMinK25l7vpfOt5pTesIPQgq2t2/Q+7eYY0o2uvwhfxBuOeWeO/6zwIDAQAB
rsa.private.key=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCyOcbivxDxfX8L7Azy8UeJommea3v+cu4CVSFoj1IsC+wKcd6GJZXthqbBgW4D/Q6iiAfnpkEW5xJSF9J57HMoSbYuJ9P6PLuBy0VpHP6/Ei02Ll7xJBkdUE0v5scNh/J9ZQ5QJWxAVM8MCH66Lex7dM7z7twt7tcagccj864g5v3Pmpim8fiMhJc+p3mfDwD14tzCQs74wZ7Jio59RuXiU5D1dsB0/ltLJH+qIMo8ve5erRqNVks2cDWYydn5yr5NP2NoeLmOcqeesB9FG3eXCpfZzQDAt/NIyKcrbmXu+l863mlN6wg9CCra3b9D7t5hjSja6/CF/EG455Z47/rPAgMBAAECggEACnaQ4gv0izDibglAI10d5Ysm5zmJMIF/zpw/11seqF5Uz7IqrbZ0LFss3AxksJBBNTKGQEfG53jOXwpt/WFvy0w0iVYmQDkjivWrkAW3QPFovRcQ1NhZLxrhRTAnvHggONNfeT4RMl+oPh0bj4OVsBPF+JUr0PiGIVTAI7CxJtY/tmvcuxWsy+iRfCETUpfTAhGED1RgbbTuq/aIqjJmoZf2V8APr3t2hnxmz20hQVvj9HbPaW8QkFnt/F40hewkb2QNTNyVHvAF1tpUi//pkXTst9vihkv3cvBRoOprriUopLuEVed5vYGSMIizirc7iU4GpM7YgAb5wrtHcnSAMQKBgQDP5Gah+9GzZYoyXijUKXj8dgNsgiryPHnOnsTol78B12TxwQyELs85NdanEGaNbUsOwAdV7g30Wf6oKq1+2vwFN6AiAj+S1FS3IzEXBJPyxJ9sg3jyEjYjVRSNCI5KThKAuZN9vkk1MMOJ7fc8XUFIjx0TbE0L4XiJdGuez4sjMQKBgQDbd+xTn7AhYhre/e7ln22F9C1pNS93MeS2/WniqZwyKDw9v2IfS2W521sAKwOulr/vdxLlgiQcNu8VtfUsTaNqxL9hRrFRV6qUXt/IhW5MAiA8wD941DNh6BM2O32gkIPg6Fjr7qi8D4p6qOg8ejz9BJo0cwNGyvDrr8WlG3l9/wKBgAf7+Kkd98bRDoaysRS85wWjLqx7L1UQV4lE9cENGuviLuFODcIB3jmPRMgzzAyAdxKA84csVmLdFfe1c+ZcWLOGmGLV/UURXJOQCXGd3mTDgm/zeLCrXGLtAJYODxDxgKpq9iwtI7ikP85LUmSCHGDCBlbZoPfk1/FHhF6cD/bxAoGAA4a4wFs3fEHURrLzzLK0Esvqkt8s5RBjKWGG+wJYpSGqXh+eFvyiJMtWefk29O4tJU7XeeKOa/mh+8pRpyWUM5n3rTtyi+kJr5qao+Eo9YWvOOqp2mombTNKY7uu+A56X/m7vAa4pVTml7PxD0+zfSk+xQr4CYInPtIzLcT0PccCgYAO80fLXtO/RTFLQmxQSmp23HiQ0bUpQP6PcHdo41dewy7RqJbzulwRAc0WbiUQ4/SkHU2s2ZKlC64EIYaKq3wLXPzSATHTyQj/VYWgyV593y2UbV+XSMXKPmJK8lFGuhDnV1EFl4of1KpluJ+9VLp5MDsVXYFhGHrvNVXlmP9G3A==
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=pdf-bucket
logging.level.org.springframework.security=DEBUG
spring.redis.host=10.201.32.143
spring.redis.port=6379
spring.redis.password=
spring.redis.database=0
spring.main.allow-circular-references=true
sms.url=https://sbx.sms24hours.com/SMSApi/send
esignpdf.url=https://digisignbeta.abdm.gov.in/digiSign/pdf/
esignapi.url=https://digisignbeta.abdm.gov.in/digiSign/genEspRequest
esign.name=NHAGRANTS
cors.url=https://fundreleasesbx.nha.gov.in
email.url=http://global2sbx.abdm.gov.internal/internal/v3/notification/message

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always