-- Creates the tables backing the "proposal upload" feature (Proposal + ProposalFile entities).
-- Run manually against the target database (sandbox/prod) — this project has no
-- Flyway/Liquibase migration runner and Hibernate ddl-auto is not set, so nothing
-- auto-creates these tables; apply this before deploying the app.
-- Safe to re-run: uses IF NOT EXISTS guards.

CREATE TABLE IF NOT EXISTS proposals (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      VARCHAR(64) NOT NULL UNIQUE,
    state_id        INTEGER NOT NULL REFERENCES states(id),
    financial_year  VARCHAR(16) NOT NULL,
    quarter         VARCHAR(4) NOT NULL,
    category_id     INTEGER NOT NULL,
    user_id         INTEGER NOT NULL REFERENCES users(id),
    -- ProposalStatus: 1=Pending at state due to query raised, 2=Pending at NHA State Coord,
    -- 3=Accepted by NHA State Coord, 4=Rejected by NHA State Coord. Defaults to 2 since that's
    -- the state a proposal starts in immediately after submission.
    status          INTEGER NOT NULL DEFAULT 2,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_proposals_filter
    ON proposals (state_id, financial_year, quarter, category_id);

CREATE INDEX IF NOT EXISTS idx_proposals_status
    ON proposals (status);

-- Holds the NHA State Coord's remarks when a query is raised (status=1); cleared again
-- once the coord accepts the resubmission. Added for the accept/raise-query/edit workflow.
ALTER TABLE proposals ADD COLUMN IF NOT EXISTS remarks TEXT;

-- Append-only audit trail: one row per action taken on a proposal (submit, accept,
-- raise query, edit+resubmit), so the full timeline can be reconstructed per request_id.
CREATE TABLE IF NOT EXISTS proposal_workflow_history (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id     INTEGER NOT NULL REFERENCES proposals(id),
    user_id         INTEGER NOT NULL REFERENCES users(id),
    -- WorkflowAction: SUBMITTED, ACCEPTED, QUERY_RAISED, EDITED_RESUBMITTED - see
    -- abdm_nha_grant_access.example.nha_grant.enums.WorkflowAction
    action          VARCHAR(32) NOT NULL,
    remarks         TEXT,
    status_after    INTEGER NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_proposal_workflow_history_proposal_id
    ON proposal_workflow_history (proposal_id);

CREATE TABLE IF NOT EXISTS proposal_files (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id         INTEGER NOT NULL REFERENCES proposals(id),
    heading             VARCHAR(32) NOT NULL,
    original_file_name  VARCHAR(255) NOT NULL,
    stored_file_name    VARCHAR(255) NOT NULL,
    file_path           VARCHAR(512) NOT NULL,
    content_type        VARCHAR(128),
    file_size           BIGINT,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_proposal_files_proposal_id
    ON proposal_files (proposal_id);
